services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Petitglacon\CrudController\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Petitglacon\CrudController\EventListener\UpdateListener:
    tags:
      - name: event.listener
        identifier: 'Petitglacon\CrudController\EventListener\UpdateListener'